import logging
from typing import Dict, Any
import json # For pretty printing in run method

from cacm_adk_core.agents.base_agent import Agent
from cacm_adk_core.semantic_kernel_adapter import KernelService
from cacm_adk_core.context.shared_context import SharedContext # Added

# logger = logging.getLogger(__name__) # Will use instance logger

class ReportGenerationAgent(Agent):
    """
    Agent responsible for generating reports based on provided data and analysis.
    """
    def __init__(self, kernel_service: KernelService):
        """
        Initializes the ReportGenerationAgent.

        Args:
            kernel_service (KernelService): The service providing access to the Semantic Kernel.
        """
        super().__init__(agent_name="ReportGenerationAgent", kernel_service=kernel_service)

    async def run(self, task_description: str, current_step_inputs: Dict[str, Any], shared_context: SharedContext) -> Dict[str, Any]:
        """
        Executes the report generation task.

        Args:
            task_description (str): Description of the report to be generated.
            current_step_inputs (Dict[str, Any]): Inputs specific to this step.
            shared_context (SharedContext): The shared context for this CACM run.

        Returns:
            Dict[str, Any]: Results of the execution, including status and report reference/content.
        """
        self.logger.info(f"'{self.agent_name}' received task: {task_description} with inputs: {current_step_inputs}")
        self.logger.info(f"Operating with SharedContext ID: {shared_context.get_session_id()} (CACM ID: {shared_context.get_cacm_id()})")

        # Retrieve Data from SharedContext
        company_name = shared_context.get_data("company_name", "N/A")
        company_ticker = shared_context.get_data("company_ticker", "N/A")
        
        key_ratios_data = shared_context.get_data("calculated_key_ratios", {}) # Expected: {"current_ratio": ..., "debt_to_equity_ratio": ...}
        current_ratio = key_ratios_data.get("current_ratio", "N/A")
        debt_to_equity_ratio = key_ratios_data.get("debt_to_equity_ratio", "N/A")
        
        financial_summary = shared_context.get_data("financial_performance_summary_text", "[Financial Performance Summary Not Available]")
        risk_summary = shared_context.get_data("key_risks_summary_text", "[Key Risks Summary Not Available]")
        overall_assessment = shared_context.get_data("overall_assessment_text", "[Overall Assessment Not Available]")
        
        self.logger.info(f"Retrieved data for report generation. Company: {company_name}")

        # Assemble Report String
        report_sections = []
        
        report_title_detail = current_step_inputs.get("report_title_detail", "Credit Analysis Report")
        report_sections.append(f"# {report_title_detail} for {company_name}")
        report_sections.append(f"## Task: {task_description}")
        report_sections.append(f"Generated by: {self.agent_name} for CACM ID: {shared_context.get_cacm_id()} (Session: {shared_context.get_session_id()})")
        report_sections.append("---") # Horizontal rule

        # Section 1: Company Overview
        report_sections.append("### 1. Company Overview")
        report_sections.append(f"**Company Name:** {company_name}")
        report_sections.append(f"**Ticker:** {company_ticker}")
        
        # Section 2: Key Financial Ratios
        report_sections.append("\n### 2. Key Financial Ratios")
        report_sections.append(f"- **Current Ratio:** {current_ratio}")
        report_sections.append(f"- **Debt-to-Equity Ratio:** {debt_to_equity_ratio}")
        # Add more ratios here if they become available in SharedContext
        
        # Section 3: Financial Performance Summary
        report_sections.append("\n### 3. Financial Performance Summary")
        report_sections.append(financial_summary)
        
        # Section 4: Key Risks Summary
        report_sections.append("\n### 4. Key Risks Summary")
        report_sections.append(risk_summary)
        
        # Section 5: Overall Assessment
        report_sections.append("\n### 5. Overall Assessment")
        report_sections.append(overall_assessment)
        
        # Include any data passed directly via current_step_inputs for this report generation step
        if current_step_inputs:
            report_sections.append("\n### 6. Additional Report Parameters")
            report_sections.append(f"```json\n{json.dumps(current_step_inputs, indent=2)}\n```")

        # Optionally, include data received via direct inter-agent communication (receive_analysis_results)
        if hasattr(self, 'stored_results') and self.stored_results:
            report_sections.append("\n### 7. Data Received from Other Agents")
            for i, res_item in enumerate(self.stored_results):
                report_sections.append(f"**Item {i+1} from Agent '{res_item.get('from', 'Unknown')}':**")
                report_sections.append(f"```json\n{json.dumps(res_item.get('data',{}), indent=2)}\n```")
        
        final_report_string = "\n\n".join(report_sections) # Using double newline for markdown paragraph breaks
            
        self.logger.info(f"Report assembled. Length: {len(final_report_string)}")
        
        return {
            "status": "success",
            "agent": self.agent_name,
            "message": "Report generated successfully from SharedContext data.",
            "generated_report_text": final_report_string
        }

    async def receive_analysis_results(self, sending_agent_name: str, results: Dict[str, Any]):
        """
        Receives analysis results from another agent.
        """
        self.logger.info(f"'{self.agent_name}' received analysis results from '{sending_agent_name}'.")
        # Store or process these results
        if not hasattr(self, 'stored_results'):
            self.stored_results = []
        self.stored_results.append({ "from": sending_agent_name, "data": results})
        self.logger.info(f"Results from '{sending_agent_name}' stored. Total stored items: {len(self.stored_results)}")


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    from semantic_kernel import Kernel
    # Mock KernelService for testing
    import json # Added for pretty printing in test run
    class MockKernelService(KernelService):
        def __init__(self):
            self._kernel = Kernel() 
            self.logger_main = logging.getLogger("__main__") # Use main logger for mock service logs
            self.logger_main.info("MockKernelService for ReportGenerationAgent initialized.")

        def get_kernel(self):
            return self._kernel
        
        def _initialize_kernel(self): pass

    mock_service = MockKernelService()
    report_agent = ReportGenerationAgent(kernel_service=mock_service)

    import asyncio
    async def test_run():
        mock_shared_context_report = SharedContext(cacm_id="test_report_gen_cacm")
        # Simulate AnalysisAgent having stored some results via receive_analysis_results
        await report_agent.receive_analysis_results(
            "AnalysisAgent_Test", 
            {"summary": "Test analysis summary", "value": 42}
        )
        # Simulate DataIngestionAgent having added a doc ref
        mock_shared_context_report.add_document_reference("10K_FILING", "processed/XYZ_10K_2023.txt")

        result = await report_agent.run(
            task_description="Generate a final financial overview.",
            current_step_inputs={"report_title_detail": "Q1 Financial Overview", "audience": "management"},
            shared_context=mock_shared_context_report
        )
        logging.info(f"ReportGenerationAgent run result:\n{result.get('report_content')}")
        mock_shared_context_report.log_context_summary()

    asyncio.run(test_run())
